[project]
name = "quantum-annealing-for-sudoku"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.0.0",
    "matplotlib>=3.3.0",
    "notebook>=6.4.0",
    "numpy>=1.20.0",
    "seaborn>=0.11.0",
]
